# Generated by Django 3.2 on 2021-04-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210411_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='<django.db.models.fields.CharField>-<django.db.models.fields.DateField>', max_length=255),
        ),
    ]
